### ISSUE TITLE
Linux/Mac support

### ISSUE THREAD

**Issue by katyo** [OptimisticPeach/dart-sys#1]
According to
https://dart.dev/server/c-interop-native-extensions#appendix-compiling-and-linking-extensions
only on windows we need linking with _dart.lib_, so we can simply skip this step on unix.

**Comment by izolyomi** [comment]
Are there any plans to support Unix/Mac? If so, does someone have any updates?

**Comment by OptimisticPeach** [comment]
I'm currently taking care of another personal project. I plan on being done within a week or so (Probably less). I will continue progress on this afterwards.

**Comment by OptimisticPeach** [comment]
I'll start work on this now. I don't have access to a Mac for testing, but I will try to make do. If someone is willing to test on a Mac, that would be wonderful.

**Comment by OptimisticPeach** [comment]
This should be resolved by #2.
